version: '3.2'
services:
  master:
    image: ${master_repo}:${master_tag}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure
    ports:
      - 8080:8080
    command: ["/master", "-etcd-endpoints=${etcd}"]

  gravity:
    image: ${gravity_repo}:${gravity_tag}
    environment:
      DRC_LABELS: "version=${gravity_tag}"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure
    ports:
      - 8080
    command: ["/gravity", "-etcd-endpoints=${etcd}"]

  nuclear:
    image: ${nuclear_repo}:${nuclear_tag}
    environment:
      DRC_LABELS: "version=${nuclear_tag}"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure
    ports:
      - 8080
    command: ["/nuclear", "-etcd-endpoints=${etcd}"]

  scanner:
    image: ${scanner_repo}:${scanner_tag}
    environment:
      DRC_LABELS: "version=${scanner_tag}"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure
    ports:
      - 8080
    command: ["/scanner", "-etcd-endpoints=${etcd}"]

  admin:
    image: ${admin_repo}:${admin_tag}
    restart: on-failure
    ports:
      - 80:80