## mysql image version
## ref: https://hub.docker.com/r/library/mysql/tags/
##
image: "mysql"
imageTag: "5.7.14"

persistence:
  enabled: false
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 8Gi
  annotations: {}


## Specify password for root user
##
## Default: random 10 character string
mysqlRootPassword: ""

## Create a database user
##
mysqlUser: drc
## Default: random 10 character string
mysqlPassword: "test123"

## Allow unauthenticated access, uncomment to enable
##
mysqlAllowEmptyPassword: true

# Custom mysql configuration files used to override default mysql settings
configurationFiles:
  mysql.cnf: |-
    [mysqld]
    server_id=4
    log_bin=mysql-bin
    gtid-mode=ON
    enforce-gtid-consistency=ON