nameOverride: ""
fullnameOverride: ""

deploymentRules:
  - group: "default"
    pipelines: ["*"]
    image: "docker.mobike.io/database/drc/drc:156a28a4"
    command: ["/drc", "-config=/etc/drc/config.json"]

operator:
  image:
    repository: docker.mobike.io/database/drc/operator
    tag: 156a28a4
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources: {}
#    limits:
#      cpu: 2
#      memory: 500M
#    requests:
#      cpu: 0.5
#      memory: 100M

tags:
  gatekeeper: true

admin:
  image:
    repository: docker.mobike.io/database/drc-admin
    tag: 59d44f7c
    pullPolicy: IfNotPresent
  service:
    port: 80
    nodePort: 30066
  resources: {}
#    limits:
#      cpu: 100m
#      memory: 100M
#    requests:
#      cpu: 100m
#      memory: 100M

gatekeeper:
  image:
    repository: docker.mobike.io/database/drc/gatekeeper
    tag: 156a28a4
    pullPolicy: IfNotPresent
  resources: {}
  #    requests:
  #      cpu: 100m
  #      memory: 100M
  service:
    port: 80
    nodePort: 30067
  mysql:
    source: root@tcp(source-mysql:3306)/?interpolateParams=true&parseTime=true&collation=utf8mb4_general_ci&loc=Local
    target: root@tcp(target-mysql:3306)/?interpolateParams=true&parseTime=true&collation=utf8mb4_general_ci&loc=Local
  cases:
    - name: simple
      nrTables: 10
      nrSeedRows: 10000
      deleteRatio: 0.2
      insertRatio: 0.5
      concurrency: 20
      transactionLength: 5

drc:
  service:
    port: 80