version: '3.2'
services:
  registrator:
    image: docker.mobike.io/database/registrator:1.1.0
    container_name: registrator
    restart: always
    environment:
      ETCDCTL_API: 3
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: ["/bin/registrator", "--cleanup", "--ip", "localhost", "etcd://localhost:2379/services"]

  fluent-bit:
    image: fluent/fluent-bit:0.13
    container_name: fluent-bit
    network_mode: host
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/log:/var/log/host
      - /opt/docker/containers:/opt/docker/containers
    restart: always
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]