position-file = "gravity.meta"

[pipeline]
name = "mongo-test"
input = "mongo"
output = "kafka"
output-format = "pb"
route-mode = "static"

[[pipeline.mongo.mongo-sources]]
[pipeline.mongo.mongo-sources.source]
host = "127.0.0.1"
username = ""
password = ""

[pipeline.kafka-global]
broker-addrs = ["mbk-dev02.oceanbase.org.cn:9092"]

[pipeline.kafka-global.partitions]
"ryan_test" = 1

[[pipeline.static-route-config.routes]]
source-db = "src"
source-table = "test_collection"
dml-target-topic = "ryan_test"