name = "test"

[input.mysql]
mode = "stream"

[input.mysql.source]
host = "127.0.0.1"
username = "root"
password = ""
port = 3306

[output.mysql.target]
host = "127.0.0.1"
username = "root"
password = ""
port = 3306

[[output.mysql.routes]]
match-schema = "test"
match-table = "t"
target-table = "t1"