name = "example-mongo2kafka"

[input.mongooplog.source]
host = "127.0.0.1"
port = 27017

[output.async-kafka.kafka-global-config]
broker-addrs = ["localhost:9092"]

[[output.async-kafka.routes]]
match-schema = "test"
match-table = "test_table"
dml-topic = "test.test_table"

[system.scheduler]
type = "batch-table-scheduler"
nr-worker = 1
batch-size = 2
queue-size = 1024
sliding-window-size = 1024
