apiVersion: v1
kind: Service
metadata:
  name: {{ include "drc-operator.fullname" . }}-admin
  labels:
    app.kubernetes.io/name: {{ include "drc-operator.name" . }}-admin
    helm.sh/chart: {{ include "drc-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.admin.service.port }}
      targetPort: http
      nodePort: {{ .Values.admin.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "drc-operator.name" . }}-admin
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drc-operator.fullname" . }}-admin
  labels:
    app.kubernetes.io/name: {{ include "drc-operator.name" . }}-admin
    helm.sh/chart: {{ include "drc-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  drc.conf: |
    server {
      listen       80;
      server_name  localhost;

      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }

      location /api/ {
        proxy_pass http://{{ include "drc-operator.fullname" . }}:{{ .Values.operator.service.port }}/;
      }

      location /health {
              access_log off;
              return 200 "healthy";
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drc-operator.fullname" . }}-admin
  labels:
    app.kubernetes.io/name: {{ include "drc-operator.name" . }}-admin
    helm.sh/chart: {{ include "drc-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "drc-operator.name" . }}-admin
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "drc-operator.name" . }}-admin
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      volumes:
        - name: ng-conf
          configMap:
            name: {{ include "drc-operator.fullname" . }}-admin
      containers:
        - name: admin
          image: "{{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag }}"
          imagePullPolicy: {{ .Values.admin.image.pullPolicy }}
          volumeMounts:
            - name: ng-conf
              mountPath: /etc/nginx/conf.d
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
          {{- if .Values.admin.resources }}
          resources:
  {{ toYaml .Values.admin.resources | indent 10 }}
  {{- end }}