apiVersion: v1
kind: Service
metadata:
  name: drc
  labels:
    app.kubernetes.io/name: drc
    helm.sh/chart: {{ include "drc-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: http
      port: {{ .Values.drc.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: drc